### ISSUE TITLE
ETA?

### ISSUE THREAD

**Issue by charlieball** [dkd/smartr#1]
Hi.

This looks a bit promising, but when do you think it will be mature enough to give it a try?

**Comment by dkd** [comment]
Hi. We use this in production at our company. give it a try!

**Comment by KieranHayes** [comment]
I am gonna release a stable version for the public within the next 4 weeks. I am currently working on tests and some missing admin features.

**Comment by charlieball** [comment]
That sounds good, looking forward to that :)
