### ISSUE TITLE
Wrong sorting of unanswered questions

### ISSUE THREAD

**Issue by flippingbits** [dkd/smartr#3]
Hi,

at the moment, unanswered questions are sorted by their id.
It would be nice, if you can sort them by their created_at attribute, in order to have the newest unanswered questions at the top.

Best regards

**Comment by flippingbits** [comment]
Resolved this in http://github.com/flippingbits/smartr/commit/363d6515424aaa64106cd8cc6d01d06707ee76e6

I've send you a pull request.

**Comment by KieranHayes** [comment]
Done.

**Comment by flippingbits** [comment]
Thanks!
