### ISSUE TITLE
Mass assignment of users

### ISSUE THREAD

**Issue by flippingbits** [dkd/smartr#8]
When editing my user account I can add a field "user[is_admin]" that equals 1. This would grant my account admin permissions.

Please fix this by using

```
attr_accessible
```

for a whitelist filter or

```
attr_protected
```

for a blacklist filter.

**Comment by flippingbits** [comment]
Seems that this is already fixed in branch "rails3edition".

**Comment by KieranHayes** [comment]
yep.
