### ISSUE TITLE
Rake db:migrate fails

### ISSUE THREAD

**Issue by elfassy** [dkd/smartr#9]
```
rake aborted!
undefined method `has_friendly_id' for Question(Table doesn't exist):Class
```

Is there a demo anywhere of this app to avoid everyone having to build?

**Comment by KieranHayes** [comment]
There is currently no demo available. Sorry.
- Checkout the Master Branch
- Run bundle install
- cp config/database.yml.example config/database.yml
- run bundle exec rake db:migrate
- bundle exec rake sunspot:solr:start

**Please note that I am working on a updated version on the rails31 branch. You might want to wait unti that version is ready.**
